language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

arch:
  - amd64
  - arm64

env:
  - BUILD=
  - BUILD=static
  - BUILD=all

jobs:
  exclude:
    - os: osx
      compiler: gcc
      env: BUILD=static
    - os: osx
      compiler: clang
      env: BUILD=static
    - os: linux
      compiler: gcc
      arch: arm64
      env: BUILD=all
    - os: linux
      compiler: clang
      arch: arm64
      env: BUILD=all

before_install:
  - sh .github/travis/before-install.sh

script:
  - sh .github/travis/build.sh
