language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - BUILD=
  - BUILD=static

jobs:
  exclude:
    - os: osx
    - compiler: gcc
    - env: BUILD=static
  exclude:
    - os: osx
    - compiler: clang
    - env: BUILD=static

before_install:
  - sh .github/travis/before-install.sh

script:
  - sh .github/travis/build.sh
