os:
    - linux
    - osx

language: c

matrix:
    include:
        - compiler: gcc
        - compiler: clang

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install bison autotools-dev libncurses5-dev libevent-dev pkg-config libutempter-dev build-essential; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi

script:
    - ./autogen.sh && ./configure && make
